### ISSUE TITLE
Geordi Setup: Undefined method `captures' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#127]
```
% g setup 

# Creating config/database.yml
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.2.0/lib/geordi/commands/create_database_yml.rb:10:in `create_database_yml': undefined method `captures' for nil:NilClass (NoMethodError)
```

* ruby 2.3.0
* geordi 4.2.0

Introduced with b4552632948372520e9e40e753ace89919dc8255.

Example Bad:

```
sample = "development:\r\n  adapter: mysql2\r\n  database: test_project\r\n  encoding: utf8\r\n  username: root\r\n  password: some-password\r\n"
sample.match(/adapter: (\w+)\n/)
=> nil
```

Example Good:

```
sample = "development:\n  adapter: mysql2\n  database: test_project\n  encoding: utf8\n  username: root\n  password: some-password\n"
sample.match(/adapter: (\w+)\n/)
=> #<MatchData "adapter: mysql2\n" 1:"mysql2">
```

Long story short, we have projects that still uses `\r\n`.

Options:
* Show a proper error message, that `\r\n` is not supported.
* Adjust the Regex. Note that `$INPUT_RECORD_SEPARATOR` is just the used value of the system and not in the file.

**Comment by codener** [comment]
Geordi should match `/adapter: (\w+)$/`; actually `/adapter: (\w+)/` should be good enough.
